# 01 Data Loading and Cleaning

This notebook loads the NYC restaurant inspection dataset, checks missingness and structure, and performs the initial cleaning and year filtering used throughout the project.

In [4]:
# Author: Jessica
# Loading packages used in this notebook

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
# Author: Jessica
# Loading the raw inspection dataset so this notebook runs independently

df = pd.read_csv("https://data.cityofnewyork.us/api/views/43nn-pn8j/rows.csv?accessType=DOWNLOAD")
print(df.shape)
df.head()

(296751, 27)

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,...,INSPECTION TYPE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA,Location
0,50176910,BOLO BOLO,Brooklyn,196,COURT STREET,11201.0,6148040762,NaN,01/01/1900,NaN,...,NaN,40.687204,-73.993575,306.0,39.0,4500.0,3003277.0,3.003020e+09,BK33,POINT (-73.993574528117 40.687204145668)
1,50178030,L'ARTIGIANO GELATO,Queens,90-15,QUEENS BOULEVARD,11373.0,9176627728,NaN,01/01/1900,NaN,...,NaN,40.733840,-73.871577,404.0,25.0,68300.0,4045999.0,4.018600e+09,QN29,POINT (-73.871577033806 40.733840182011)
2,50153097,FIORE HARLEM,Manhattan,333,LENOX AVENUE,10027.0,9177504302,NaN,01/01/1900,NaN,...,NaN,40.808866,-73.944694,110.0,9.0,22400.0,1057867.0,1.019110e+09,MN03,POINT (-73.944694448448 40.808866256729)
3,50173513,228 ASIAN BISTRO,Brooklyn,228,DUFFIELD STREET,11201.0,3473921179,NaN,01/01/1900,NaN,...,NaN,40.691298,-73.984393,302.0,33.0,1500.0,3424452.0,3.001450e+09,BK38,POINT (-73.984393290305 40.691298465676)
4,41395397,CITI FIELD PAT LAFRIEDA/KOSHER GRILL - STAND 142,Queens,126 ST,and ROOSEVELT AVENUE,NaN,7185958100,American,09/13/2025,No violations were recorded at the time of thi...,...,Cycle Inspection / Initial Inspection,0.000000,0.000000,NaN,NaN,NaN,NaN,4.000000e+00,NaN,NaN

## Uploading Data
This notebook performs initial exploratory data analysis (EDA) on the restaurant inspection dataset to understand its structure, contents, and basic statistics.

In [6]:
%pip install pandas

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [7]:
# uploading data 
import pandas as pd

# NYC Open Data CSV download link
url = "https://data.cityofnewyork.us/api/views/43nn-pn8j/rows.csv?accessType=DOWNLOAD"

# Read directly from the web
df = pd.read_csv(url)

print("Shape:", df.shape)

# Preview
df.head()

Shape: (296751, 27)

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,...,INSPECTION TYPE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA,Location
0,50176910,BOLO BOLO,Brooklyn,196,COURT STREET,11201.0,6148040762,NaN,01/01/1900,NaN,...,NaN,40.687204,-73.993575,306.0,39.0,4500.0,3003277.0,3.003020e+09,BK33,POINT (-73.993574528117 40.687204145668)
1,50178030,L'ARTIGIANO GELATO,Queens,90-15,QUEENS BOULEVARD,11373.0,9176627728,NaN,01/01/1900,NaN,...,NaN,40.733840,-73.871577,404.0,25.0,68300.0,4045999.0,4.018600e+09,QN29,POINT (-73.871577033806 40.733840182011)
2,50153097,FIORE HARLEM,Manhattan,333,LENOX AVENUE,10027.0,9177504302,NaN,01/01/1900,NaN,...,NaN,40.808866,-73.944694,110.0,9.0,22400.0,1057867.0,1.019110e+09,MN03,POINT (-73.944694448448 40.808866256729)
3,50173513,228 ASIAN BISTRO,Brooklyn,228,DUFFIELD STREET,11201.0,3473921179,NaN,01/01/1900,NaN,...,NaN,40.691298,-73.984393,302.0,33.0,1500.0,3424452.0,3.001450e+09,BK38,POINT (-73.984393290305 40.691298465676)
4,41395397,CITI FIELD PAT LAFRIEDA/KOSHER GRILL - STAND 142,Queens,126 ST,and ROOSEVELT AVENUE,NaN,7185958100,American,09/13/2025,No violations were recorded at the time of thi...,...,Cycle Inspection / Initial Inspection,0.000000,0.000000,NaN,NaN,NaN,NaN,4.000000e+00,NaN,NaN

## Missing Values Analysis

In [8]:
# Display statistical summary
print("Statistical Summary:")
df.describe()

Statistical Summary:

,CAMIS,ZIPCODE,SCORE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL
count,2.967510e+05,293550.000000,279940.000000,295108.000000,295108.000000,291936.000000,291963.000000,291963.000000,2.907130e+05,2.951080e+05
mean,4.808145e+07,10706.651947,25.222805,40.290575,-73.145502,255.024303,20.568887,29893.289739,2.587286e+06,2.479677e+09
std,3.742506e+06,618.017539,18.816117,4.200326,7.624870,130.362590,15.659157,31277.088356,1.356139e+06,1.338271e+09
min,3.007544e+07,6605.000000,0.000000,0.000000,-74.249101,101.000000,1.000000,100.000000,1.000000e+06,1.000000e+00
25%,5.000507e+07,10023.000000,12.000000,40.686731,-73.988588,106.000000,4.000000,8000.000000,1.051506e+06,1.011150e+09
50%,5.009320e+07,11101.000000,21.000000,40.732861,-73.955557,302.000000,20.000000,17500.000000,3.022102e+06,3.008100e+09
75%,5.013052e+07,11232.000000,33.000000,40.761237,-73.893554,402.000000,34.000000,42600.000000,4.011658e+06,4.006350e+09
max,5.018322e+07,69361.000000,203.000000,40.912822,0.000000,595.000000,51.000000,162100.000000,5.799501e+06,5.270001e+09

## Statistical Summary

In [9]:

print(f"Shape: {df.shape}")

Shape: (296751, 27)

In [10]:
# Display data types and info
print("\nData Types and Info:")
df.info()

Data Types and Info:
<class 'pandas.DataFrame'>
RangeIndex: 296751 entries, 0 to 296750
Data columns (total 27 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   CAMIS                  296751 non-null  int64
 1   DBA                    296749 non-null  str
 2   BORO                   296751 non-null  str
 3   BUILDING               295770 non-null  str
 4   STREET                 296748 non-null  str
 5   ZIPCODE                293550 non-null  float64
 6   PHONE                  296680 non-null  str
 7   CUISINE DESCRIPTION    293282 non-null  str
 8   INSPECTION DATE        296751 non-null  str
 9   ACTION                 293332 non-null  str
 10  VIOLATION CODE         291029 non-null  str
 11  VIOLATION DESCRIPTION  291029 non-null  str
 12  CRITICAL FLAG          296751 non-null  str
 13  SCORE                  279940 non-null  float64
 14  GRADE                  146126 non-null  str
 15  GRADE DATE             136557 non-null  str
 16  RECORD DATE            296751 non-null  str
 17  INSPECTION TYPE        293332 non-null  str
 18  Latitude               295108 non-null  float64
 19  Longitude              295108 non-null  float64
 20  Community Board        291936 non-null  float64
 21  Council District       291963 non-null  float64
 22  Census Tract           291963 non-null  float64
 23  BIN                    290713 non-null  float64
 24  BBL                    295108 non-null  float64
 25  NTA                    291936 non-null  str
 26  Location               291936 non-null  str
dtypes: float64(9), int64(1), str(17)
memory usage: 61.1 MB

In [11]:
#See how many null values are in each column --zeek
print(df.isnull().sum())

CAMIS                         0
DBA                           2
BORO                          0
BUILDING                    981
STREET                        3
ZIPCODE                    3201
PHONE                        71
CUISINE DESCRIPTION        3469
INSPECTION DATE               0
ACTION                     3419
VIOLATION CODE             5722
VIOLATION DESCRIPTION      5722
CRITICAL FLAG                 0
SCORE                     16811
GRADE                    150625
GRADE DATE               160194
RECORD DATE                   0
INSPECTION TYPE            3419
Latitude                   1643
Longitude                  1643
Community Board            4815
Council District           4788
Census Tract               4788
BIN                        6038
BBL                        1643
NTA                        4815
Location                   4815
dtype: int64

In [12]:
#get rid of nulls
def clean_restaurant_inspection_data(df):
    # Make a copy to avoid modifying original
    df_clean = df.copy()
    
    # Basic info cleaning
    df_clean['DBA'] = df_clean['DBA'].fillna("Unknown Business")
    df_clean['BUILDING'] = df_clean['BUILDING'].fillna("No Number")
    df_clean['STREET'] = df_clean['STREET'].fillna("Unknown Street")
    df_clean['PHONE'] = df_clean['PHONE'].fillna("No Phone Listed")
    
    # Zipcode by borough
    df_clean['ZIPCODE'] = df_clean.groupby('BORO')['ZIPCODE'].transform(lambda x: x.fillna(x.median()))
    
    # Inspection related
    df_clean['CUISINE DESCRIPTION'] = df_clean['CUISINE DESCRIPTION'].fillna("Unspecified")
    df_clean['ACTION'] = df_clean['ACTION'].fillna("No Action Recorded")
    df_clean['INSPECTION TYPE'] = df_clean['INSPECTION TYPE'].fillna("Unspecified")
    df_clean['VIOLATION CODE'] = df_clean['VIOLATION CODE'].fillna("No Violation")
    df_clean['VIOLATION DESCRIPTION'] = df_clean['VIOLATION DESCRIPTION'].fillna("No Violation Found")
    
    # Grades and scores
    df_clean['SCORE'] = df_clean['SCORE'].fillna(-1)
    df_clean['GRADE'] = df_clean['GRADE'].fillna("Not Graded")
    df_clean['GRADE DATE'] = df_clean['GRADE DATE'].fillna(df_clean['INSPECTION DATE'])
    
    # Location data
    for coord in ['Latitude', 'Longitude']:
        df_clean[coord] = df_clean.groupby('BORO')[coord].transform(lambda x: x.fillna(x.median()))
    
    # Administrative boundaries - FIX HERE
    admin_cols = ['Community Board', 'Council District', 'Census Tract', 'NTA']
    for col in admin_cols:
        df_clean[col] = df_clean.groupby('BORO')[col].transform(lambda x: 
            x.fillna(x.mode().iloc[0] if not x.mode().empty else -1))
    
    # Building numbers
    df_clean['BIN'] = df_clean['BIN'].fillna(0)
    df_clean['BBL'] = df_clean['BBL'].fillna(0)
    
    # Location string
    df_clean['Location'] = df_clean['Location'].fillna('Unknown Location')
    
    return df_clean

In [13]:
# Import Required Libraries
!pip install matplotlib
!pip install seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set display options
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

Requirement already satisfied: matplotlib in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (2.4.3)
Requirement already satisfied: packaging>=20.0 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: seaborn in /usr/local/python/3.12.1/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from seaborn) (2.4.3)
Requirement already satisfied: pandas>=1.2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from seaborn) (3.0.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Requirement already satisfied: pyparsing>=3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [14]:
# Our new filtered year
df["INSPECTION DATE"] = pd.to_datetime(df["INSPECTION DATE"], errors="coerce")

# Filter from 2022 to 2025
df_filtered_2022_2025 = df[
    (df["INSPECTION DATE"].dt.year >= 2022) &
    (df["INSPECTION DATE"].dt.year <= 2025)
]

# Check shape
print("Filtered Shape (2022–2025):", df_filtered_2022_2025.shape)

# Preview
df_filtered_2022_2025.head()

Filtered Shape (2022–2025): (271481, 27)

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION CODE,VIOLATION DESCRIPTION,CRITICAL FLAG,SCORE,GRADE,GRADE DATE,RECORD DATE,INSPECTION TYPE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA,Location
4,41395397,CITI FIELD PAT LAFRIEDA/KOSHER GRILL - STAND 142,Queens,126 ST,and ROOSEVELT AVENUE,NaN,7185958100,American,2025-09-13,No violations were recorded at the time of this inspection.,NaN,NaN,Not Applicable,0.0,A,09/13/2025,03/18/2026,Cycle Inspection / Initial Inspection,0.000000,0.000000,NaN,NaN,NaN,NaN,4.000000e+00,NaN,NaN
7,50104788,LOULOU,Manhattan,176,8 AVENUE,10011.0,9172925624,French,2023-11-08,Violations were cited in the following area(s).,02B,Hot TCS food item not held at or above 140 °F.,Critical,29.0,C,11/08/2023,03/18/2026,Cycle Inspection / Re-inspection,40.742742,-74.000328,104.0,3.0,8700.0,1013890.0,1.007680e+09,MN13,POINT (-74.000328399123 40.742741971093)
8,41486460,RIVER DELI,Brooklyn,2834,COLUMBIA PLACE,NaN,7182549200,Italian,2022-08-20,Violations were cited in the following area(s).,06E,"Sanitized equipment or utensil, including in-use food dispensing utensil, improperly used or stored.",Critical,12.0,A,08/20/2022,03/18/2026,Cycle Inspection / Initial Inspection,0.000000,0.000000,NaN,NaN,NaN,NaN,3.000000e+00,NaN,NaN
9,41585425,LUCKY GARDEN,Bronx,305,WYCKOFF AVENUE,NaN,7184181002,Chinese,2025-12-16,Violations were cited in the following area(s).,28-06,Contract with a pest management professional not in place. Record of extermination activities not kept on premises.,Not Critical,27.0,NaN,NaN,03/18/2026,Cycle Inspection / Initial Inspection,0.000000,0.000000,NaN,NaN,NaN,NaN,2.000000e+00,NaN,NaN
17,50088988,CITY ONE,Manhattan,2726,FREDERICK DOUGLASS BOULEVARD,NaN,2123688818,Chinese,2023-08-31,Violations were cited in the following area(s).,08A,"Establishment is not free of harborage or conditions conducive to rodents, insects or other pests.",Not Critical,15.0,B,08/31/2023,03/18/2026,Cycle Inspection / Re-inspection,0.000000,0.000000,NaN,NaN,NaN,NaN,1.000000e+00,NaN,NaN

In [15]:
print("Original:", df.shape)
print("2022–2025:", df_filtered_2022_2025.shape)

print(
    df_filtered_2022_2025["INSPECTION DATE"].min(),
    "to",
    df_filtered_2022_2025["INSPECTION DATE"].max()
)

Original: (296751, 27)
2022–2025: (271481, 27)
2022-01-03 00:00:00 to 2025-12-31 00:00:00

## Saved Output

This notebook saves a cleaned version of the filtered dataset for use in later notebooks.

In [18]:
# Author: Jessica
# Creating shared_data folder if it doesn’t exist, then saving cleaned dataset

import os

os.makedirs("shared_data", exist_ok=True)

cleaned_path = "shared_data/cleaned_inspections.csv"
df_filtered_2022_2025.to_csv(cleaned_path, index=False)

print(f"Saved cleaned dataset to {cleaned_path}")

Saved cleaned dataset to shared_data/cleaned_inspections.csv