# 01 Data Loading and Cleaning

This notebook loads the NYC restaurant inspection dataset, checks missingness and structure, and performs the initial cleaning and year filtering used throughout the project.

In [1]:
!pip install Pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: Pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.2)
Requirement already satisfied: numpy in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.4.4)
Requirement already satisfied: matplotlib in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.10.8)
Requirement already satisfied: seaborn in /usr/local/python/3.12.1/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: scikit-learn in /usr/local/python/3.12.1/lib/python3.12/site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from Pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->Pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [2]:
"""# Author: Jessica
# Loading packages used in this notebook

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt"""

'# Author: Jessica\n# Loading packages used in this notebook\n\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt'

In [3]:
# Author: Jessica
# Loading the raw inspection dataset so this notebook runs independently

"""df = pd.read_csv("https://data.cityofnewyork.us/api/views/43nn-pn8j/rows.csv?accessType=DOWNLOAD")
print(df.shape)
df.head()"""

'df = pd.read_csv("https://data.cityofnewyork.us/api/views/43nn-pn8j/rows.csv?accessType=DOWNLOAD")\nprint(df.shape)\ndf.head()'

## Uploading Data
This notebook performs initial exploratory data analysis (EDA) on the restaurant inspection dataset to understand its structure, contents, and basic statistics.

In [4]:
%pip install pandas

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [5]:
# uploading data 
import pandas as pd

# NYC Open Data CSV download link
url = "https://data.cityofnewyork.us/api/views/43nn-pn8j/rows.csv?accessType=DOWNLOAD"

# Read directly from the web
df = pd.read_csv(url)

print("Shape:", df.shape)

# Preview
df.head()

Shape: (295664, 27)

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,...,INSPECTION TYPE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA,Location
0,50175225,TROPICAL JERK,Queens,165-25,LIBERTY AVENUE,11433.0,5164396534,NaN,01/01/1900,NaN,...,NaN,40.702224,-73.791514,412.0,27.0,44400.0,4216231.0,4.101550e+09,QN61,POINT (-73.79151424692 40.702223564768)
1,50177804,MAD RADIO NYC,Brooklyn,395,WYTHE AVENUE,11249.0,7862410411,NaN,01/01/1900,NaN,...,NaN,40.711126,-73.966544,301.0,34.0,54900.0,3251760.0,3.024700e+09,BK73,POINT (-73.96654448749 40.711125620758)
2,50160900,JUST HOTDOGS,Brooklyn,1775,CONEY ISLAND AVENUE,11230.0,9297644404,NaN,01/01/1900,NaN,...,NaN,40.614028,-73.963128,314.0,48.0,54200.0,3429339.0,3.067490e+09,BK43,POINT (-73.96312840963 40.614028045568)
3,50182593,BABA DONER LLC,Manhattan,147,AVENUE A,10009.0,6464762979,NaN,01/01/1900,NaN,...,NaN,40.727406,-73.982559,103.0,2.0,3400.0,1077647.0,1.004370e+09,MN22,POINT (-73.982559179975 40.727405647501)
4,50184281,RICS JAMAICAN AND AMERICAN RESTAURANT INC.,Brooklyn,1503,FULTON STREET,11216.0,3477533377,NaN,01/01/1900,NaN,...,NaN,40.679957,-73.941517,303.0,36.0,26900.0,3053627.0,3.018570e+09,BK75,POINT (-73.941517274608 40.679956924731)

## Missing Values Analysis

In [6]:
# Display statistical summary
print("Statistical Summary:")
df.describe()

Statistical Summary:

,CAMIS,ZIPCODE,SCORE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL
count,2.956640e+05,292501.000000,278756.000000,294063.000000,294063.000000,290934.000000,290960.000000,290960.000000,2.896960e+05,2.940630e+05
mean,4.810666e+07,10706.337992,25.288446,40.295017,-73.153465,254.793599,20.534300,29877.054502,2.585198e+06,2.477541e+09
std,3.726772e+06,616.987684,18.953952,4.179400,7.586871,130.366611,15.653985,31277.829371,1.356356e+06,1.338142e+09
min,3.007544e+07,6605.000000,0.000000,0.000000,-74.249101,101.000000,1.000000,100.000000,1.000000e+06,1.000000e+00
25%,5.000586e+07,10023.000000,12.000000,40.686979,-73.988599,106.000000,4.000000,8000.000000,1.050747e+06,1.010870e+09
50%,5.009458e+07,11101.000000,21.000000,40.732918,-73.955685,302.000000,20.000000,17300.000000,3.022098e+06,3.008090e+09
75%,5.013120e+07,11232.000000,33.000000,40.761174,-73.893529,402.000000,34.000000,42600.000000,4.011504e+06,4.006290e+09
max,5.018465e+07,69361.000000,214.000000,40.912822,0.000000,595.000000,51.000000,162100.000000,5.799501e+06,5.270001e+09

## Statistical Summary

In [7]:

print(f"Shape: {df.shape}")

Shape: (295664, 27)

In [8]:
# Display data types and info
print("\nData Types and Info:")
df.info()

Data Types and Info:

<class 'pandas.DataFrame'>
RangeIndex: 295664 entries, 0 to 295663
Data columns (total 27 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   CAMIS                  295664 non-null  int64
 1   DBA                    295662 non-null  str
 2   BORO                   295664 non-null  str
 3   BUILDING               294687 non-null  str
 4   STREET                 295656 non-null  str
 5   ZIPCODE                292501 non-null  float64
 6   PHONE                  295585 non-null  str
 7   CUISINE DESCRIPTION    292168 non-null  str
 8   INSPECTION DATE        295664 non-null  str
 9   ACTION                 292218 non-null  str
 10  VIOLATION CODE         289892 non-null  str
 11  VIOLATION DESCRIPTION  289892 non-null  str
 12  CRITICAL FLAG          295664 non-null  str
 13  SCORE                  278756 non-null  float64
 14  GRADE                  145552 non-null  str
 15  GRADE DATE             136237 non-null  str
 16  RECORD DATE            295664 non-null  str
 17  INSPECTION TYPE        292218 non-null  str
 18  Latitude               294063 non-null  float64
 19  Longitude              294063 non-null  float64
 20  Community Board        290934 non-null  float64
 21  Council District       290960 non-null  float64
 22  Census Tract           290960 non-null  float64
 23  BIN                    289696 non-null  float64
 24  BBL                    294063 non-null  float64
 25  NTA                    290934 non-null  str
 26  Location               290934 non-null  str
dtypes: float64(9), int64(1), str(17)
memory usage: 60.9 MB

In [9]:
#See how many null values are in each column --zeek
print(df.isnull().sum())

CAMIS                         0
DBA                           2
BORO                          0
BUILDING                    977
STREET                        8
ZIPCODE                    3163
PHONE                        79
CUISINE DESCRIPTION        3496
INSPECTION DATE               0
ACTION                     3446
VIOLATION CODE             5772
VIOLATION DESCRIPTION      5772
CRITICAL FLAG                 0
SCORE                     16908
GRADE                    150112
GRADE DATE               159427
RECORD DATE                   0
INSPECTION TYPE            3446
Latitude                   1601
Longitude                  1601
Community Board            4730
Council District           4704
Census Tract               4704
BIN                        5968
BBL                        1601
NTA                        4730
Location                   4730
dtype: int64

In [10]:
#get rid of nulls
def clean_restaurant_inspection_data(df):
    # Make a copy to avoid modifying original
    df_clean = df.copy()
    
    # Basic info cleaning
    df_clean['DBA'] = df_clean['DBA'].fillna("Unknown Business")
    df_clean['BUILDING'] = df_clean['BUILDING'].fillna("No Number")
    df_clean['STREET'] = df_clean['STREET'].fillna("Unknown Street")
    df_clean['PHONE'] = df_clean['PHONE'].fillna("No Phone Listed")
    
    # Zipcode by borough
    df_clean['ZIPCODE'] = df_clean.groupby('BORO')['ZIPCODE'].transform(lambda x: x.fillna(x.median()))
    
    # Inspection related
    df_clean['CUISINE DESCRIPTION'] = df_clean['CUISINE DESCRIPTION'].fillna("Unspecified")
    df_clean['ACTION'] = df_clean['ACTION'].fillna("No Action Recorded")
    df_clean['INSPECTION TYPE'] = df_clean['INSPECTION TYPE'].fillna("Unspecified")
    df_clean['VIOLATION CODE'] = df_clean['VIOLATION CODE'].fillna("No Violation")
    df_clean['VIOLATION DESCRIPTION'] = df_clean['VIOLATION DESCRIPTION'].fillna("No Violation Found")
    
    # Grades and scores
    df_clean['SCORE'] = df_clean['SCORE'].fillna(-1)
    df_clean['GRADE'] = df_clean['GRADE'].fillna("Not Graded")
    df_clean['GRADE DATE'] = df_clean['GRADE DATE'].fillna(df_clean['INSPECTION DATE'])
    
    # Location data
    for coord in ['Latitude', 'Longitude']:
        df_clean[coord] = df_clean.groupby('BORO')[coord].transform(lambda x: x.fillna(x.median()))
    
    # Administrative boundaries - FIX HERE
    admin_cols = ['Community Board', 'Council District', 'Census Tract', 'NTA']
    for col in admin_cols:
        df_clean[col] = df_clean.groupby('BORO')[col].transform(lambda x: 
            x.fillna(x.mode().iloc[0] if not x.mode().empty else -1))
    
    # Building numbers
    df_clean['BIN'] = df_clean['BIN'].fillna(0)
    df_clean['BBL'] = df_clean['BBL'].fillna(0)
    
    # Location string
    df_clean['Location'] = df_clean['Location'].fillna('Unknown Location')
    
    return df_clean

In [11]:
# Import Required Libraries
!pip install matplotlib
!pip install seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set display options
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

Requirement already satisfied: matplotlib in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (2.4.4)
Requirement already satisfied: packaging>=20.0 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: seaborn in /usr/local/python/3.12.1/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from seaborn) (2.4.4)
Requirement already satisfied: pandas>=1.2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from seaborn) (3.0.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/codespace/.local/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [12]:
# Our new filtered year
df["INSPECTION DATE"] = pd.to_datetime(df["INSPECTION DATE"], errors="coerce")

# Filter from 2022 to 2025
df_filtered_2022_2025 = df[
    (df["INSPECTION DATE"].dt.year >= 2022) &
    (df["INSPECTION DATE"].dt.year <= 2025)
]

# Check shape
print("Filtered Shape (2022–2025):", df_filtered_2022_2025.shape)

# Preview
df_filtered_2022_2025.head()

Filtered Shape (2022–2025): (262690, 27)

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION CODE,VIOLATION DESCRIPTION,CRITICAL FLAG,SCORE,GRADE,GRADE DATE,RECORD DATE,INSPECTION TYPE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA,Location
18,50159458,ARAMARK,Manhattan,66,HUDSON YARDS,NaN,9176811142,Other,2025-03-17,Violations were cited in the following area(s).,08A,"Establishment is not free of harborage or conditions conducive to rodents, insects or other pests.",Not Critical,13.0,A,03/17/2025,04/16/2026,Pre-permit (Operational) / Initial Inspection,0.00000,0.000000,NaN,NaN,NaN,NaN,1.000000e+00,NaN,NaN
28,50058975,HOME FRITE,Brooklyn,1047,BEDFORD AVENUE,11216.0,3476273266,American,2025-10-05,No violations were recorded at the time of this inspection.,NaN,NaN,Not Applicable,0.0,NaN,NaN,04/16/2026,Inter-Agency Task Force / Initial Inspection,40.68814,-73.954852,303.0,36.0,24300.0,3050071.0,3.017930e+09,BK75,POINT (-73.954851588077 40.688139637211)
35,50099398,LECHONERA POLLO SABROSO DEL VALLE RESTAURANT,Bronx,650B,WESTCHESTER AVENUE,NaN,3472977545,Spanish,2022-11-02,Violations were cited in the following area(s).,02B,Hot TCS food item not held at or above 140 °F.,Critical,19.0,NaN,NaN,04/16/2026,Cycle Inspection / Initial Inspection,0.00000,0.000000,NaN,NaN,NaN,2004429.0,2.026230e+09,NaN,NaN
36,50150954,THE MELT SHOP,Queens,NaN,CA2L 503 LA GUARDIA,11371.0,7037237264,American,2025-07-16,Violations were cited in the following area(s).,02B,Hot TCS food item not held at or above 140 °F.,Critical,7.0,A,07/16/2025,04/16/2026,Pre-permit (Operational) / Initial Inspection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,41570719,CHICKPEA,Manhattan,NaN,PENN STATION,10121.0,2122440101,American,2025-09-23,Violations were cited in the following area(s).,06F,"Wiping cloths not stored clean and dry, or in a sanitizing solution, between uses.",Critical,54.0,NaN,NaN,04/16/2026,Cycle Inspection / Initial Inspection,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
print("Original:", df.shape)
print("2022–2025:", df_filtered_2022_2025.shape)

print(
    df_filtered_2022_2025["INSPECTION DATE"].min(),
    "to",
    df_filtered_2022_2025["INSPECTION DATE"].max()
)

Original: (295664, 27)
2022–2025: (262690, 27)
2022-01-03 00:00:00 to 2025-12-31 00:00:00

## Saved Output

This notebook saves a cleaned version of the filtered dataset for use in later notebooks.

In [14]:
# Author: Jessica
# Creating shared_data folder if it doesn’t exist, then saving cleaned dataset

import os

os.makedirs("shared_data", exist_ok=True)

cleaned_path = "shared_data/cleaned_inspections.csv"
df_filtered_2022_2025.to_csv(cleaned_path, index=False)

print(f"Saved cleaned dataset to {cleaned_path}")

Saved cleaned dataset to shared_data/cleaned_inspections.csv